xsub
c -v -c t.c
c -v -c t1.c
c -v -c t2.c
link
 -c100h -pboot=0E300h/100h,zero=0/,text/,data/,ram=8000h/,bss/ \
 -ot.com -dt.sym cpmboot.obj t.obj rt.lib libc.lib


THEN...

; edit t.sym, keep only the functions called by T1 & T2 :

1317 _Balloc
065A _RunTask512
08F0 _StopTask
0B0E _CON_Write
07A7 _IncTaskStack
09A4 _GetCrtTask
23B4 _strlen


THEN...

symtoas tbase.as t.sym
z80as tbase
link
 -ptext=4000h,data -ot1rom.obj t1.obj tbase.obj csv.obj
link
 -ptext=4000h/8000h,data/ -ot2rom.obj t2.obj tbase.obj csv.obj
objtohex t1rom.obj t1rom.hex
objtohex t2rom.obj t2rom.hex


THEN...

;burn (TROM.HEX = CP/M booter + T1ROM.HEX + T2ROM.HEX) to 512KB EPROM
; !!! CP/M booter is for 512 ROM/RAM + CF64MB + SIO !!!
;then run T.COM
