zas -j dlist.as
zas -j balloc.as
zas rtsys1.as
zas -j rtsys2.as
zas -j rtclk.as
zas -j queue.as
zas -j mailbox.as
zas -j io.as
zas -j snapshot.as
zas -j hexload.as
zas -j util.as
zas -j cmd.as
zas boot.as
zas -j csv.as
era rt.lib
libr r rt.lib rtsys1.obj rtsys2.obj cmd.obj snapshot.obj hexload.obj io.obj queue.obj rtclk.obj mailbox.obj
libr r rt.lib balloc.obj dlist.obj util.obj boot.obj csv.obj
